net:
  cloudopt:
    next:
      web:
        packageName: "net.cloudopt.next.example"
        cookieCors: "true"
      datasource:
        jdbcUrl: "jdbc:mysql://localhost:3306/cloudopt_example?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true"
        username: "root"
        password: "root"
        driverClassName: "com.mysql.cj.jdbc.Driver"
      jooq:
        pool: "net.cloudopt.next.jooq.pool.HikariCPPool"
        database: "mysql"
        showSql: "true"


